### ISSUE TITLE
Consider making spec OpenAPI

### ISSUE THREAD

**Issue by Lewiscowles1986** [audible-tools/Api-Documentation#1]
While it is a very simple API, and the documentation communicates it very well. You might not need to think about documentation at all, if you were to use Open specifications for API documentation.

https://editor.swagger.io is a tool that can help you find a suitable format to communicate schema's in. It can also help people generate API's from. In bullet form this is I guess readable.

For example:
- You have two API versions, using path-based versioning
- Version 1 is not advised. We could call this deprecated.
- In both versions the endpoint accepts a single parameter as part of the URL path
- In v1, an unstructured, plain-text response is returned
- In v2, a structured JSON response is returned
- There is no authentication
- REST / HTTP headers are not important, but User-Agent is advisable (good network citizen) to ensure attribution.

## Example OpenAPI

To write this as OpenAPI, I can generate example client and server code in several languages from the swagger tooling other developers make.

```yaml
openapi: "3.0.0"
info:
  version: 2021-04
  title: Audible AAX API
servers:
  - url: https://aax.api.j-kit.me/api
paths:
  /v2/activation/{activationBytes}:
    get:
      summary: Get AAX Decryption Key
      parameters:
        - name: activationBytes
          in: path
          required: true
          description: The Hexidecimal code, specific to the AAX file.
          example: 9eb875b484f87510b88eb389031e06790674193e
          schema:
            type: string
        - name: User-Agent
          in: header
          required: false
          description: Please attribute your clients
          example: My Really cool AAX Decryption tool
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V2Response"
  /v1/activation/{activationBytes}:
    get:
      summary: Get AAX Decryption Key
      deprecated: true
      parameters:
        - name: activationBytes
          in: path
          required: true
          description: The Hexidecimal code, specific to the AAX file.
          schema:
            type: string
        - name: User-Agent
          in: header
          required: false
          description: Please attribute your clients
          example: My Really cool AAX Decryption tool
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1Response"
components:
  schemas:
    V2Response:
      type: object
      required:
        - success
        - activationBytes
      properties:
        success:
          type: boolean
          description: Has the Decryption been successfully found?
          nullable: false
          example: true
        activationBytes:
          type: string
          description: String representation of decryption key
          nullable: false
          example: "12345678"
    V1Response:
      type: string


```

**Comment by Lewiscowles1986** [comment]
Btw specifying the versions like this is not recommended. A Better way is to have a v1 document and a v2 document. I Just didn't want to confuse things further.

**Comment by Lewiscowles1986** [comment]
& Oops on typo in V2Response requiring two fields that don't exist 😂

**Comment by Lewiscowles1986** [comment]
https://idratherbewriting.com/learnapidoc/pubapis_swagger.html is a nice write-up on generating your own self-hostable UI from the documentation. It points at using https://github.com/swagger-api/swagger-ui

If I am honest, mostly my tools come with swagger generation, like Swashbuckle for C# or various third-party plugins. But a google for "swagger"+"ui"+"nodejs" or whatever framework you are using will net you some tools that might be more appropriate and stay up-to-date.

**Comment by JKamsker** [comment]
Yea dotnet has swagger built in, i was just to lazy to go and enable it ¯\_(ツ)_/¯

**Comment by Lewiscowles1986** [comment]
It's more than I'm really into management side of source-code, CS & OpenSource and it's my last free time for a while, so get as much ticked off for now before I disappear for a bit 👍 .

**Comment by JKamsker** [comment]
@Lewiscowles1986 Please have look at https://aax.api.j-kit.me/redoc

**Comment by Lewiscowles1986** [comment]
Looks beautiful. Did you notice one of the headings says `<no summary>`?

**Comment by JKamsker** [comment]
Thank you!
Nope, but fixed it

**Comment by JKamsker** [comment]
Issue resolved. Closing now.
